name: Build Electron App

on:
  push:
    branches:
      - main  # Кожен пуш в main triggerить збірку

jobs:
  build:
    runs-on: ubuntu-latest  # Використовуємо Linux для збірки інсталяторів

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Mono and Wine
        run: |
          sudo apt update
          sudo apt install -y mono-complete wine64 wine32

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build app for ${{ matrix.platform }}
        run: npm run make --platform=${{ matrix.platform }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4  # Оновлена версія
        with:
          name: builds
          path: out/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./out/**/*  # Завантажуємо файли з папки out/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Це автоматичний токен для доступу до репозиторіїв
